postsubmits:
  ocp-power-automation/ocp4-upi-kvm:
    - name: update-github-pages-submodule
      labels:
        preset-ocp-ghdeploykey: "true"
      decorate: true
      run_if_changed: 'docs'
      branches:
        - ^master$
      spec:
        containers:
          - image: quay.io/powercloud/all-in-one:0.5
            command:
              - sh
            args:
              - -c
              - |
                set -o errexit
                mkdir -p ~/.ssh
                cp /etc/ssh-key/id_rsa* ~/.ssh/
                chmod 600 ~/.ssh/id_rsa*
                eval "$(ssh-agent -s)"
                ssh-add ~/.ssh/id_rsa
                ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
                git clone git@github.com:ocp-power-automation/ocp-power-automation.github.io.git
                cd ocp-power-automation.github.io
                git config --global user.email "ltccci@in.ibm.com"
                git config --global user.name "ltccci"
                git submodule update --init --recursive --remote docs/ocp4-upi-kvm
                git add .
                git commit -m "update ocp4-upi-kvm submodule"
                git push origin main
