---
triggers:
  - repos:
      - IBM/raksh
    join_org_url: https://github.com/IBM/raksh/blob/master/CONTRIBUTING.md
  - repos:
      - ppc64le-cloud
    join_org_url: https://github.com/ppc64le-cloud/test-infra/blob/master/README.md
    only_org_members: true
  - repos:
      - ocp-power-automation
    join_org_url: https://github.com/ocp-power-automation/ocp4-upi-powervs#contributing
    only_org_members: true
  - repos:
      - openshift-powervs
    join_org_url: https://github.com/ocp-power-automation/ocp4-upi-powervs#contributing
    only_org_members: true
  - repos:
      - trigger-prow/test-trigger
    join_org_url: https://github.com/trigger-prow/test-trigger/blob/main/README.md
  - repos:
      - Rajalakshmi-Girish/etcd
    join_org_url: https://github.com/Rajalakshmi-Girish/etcd/blob/main/README.md#contributing

approve:
  - repos:
      - IBM/raksh
    require_self_approval: false
  - repos:
      - ppc64le-cloud/test-infra
      - ppc64le-cloud/kubetest2-plugins
    require_self_approval: false
  - repos:
      - ocp-power-automation/ocp4-upi-powervs
      - ocp-power-automation/ocp4-playbooks
      - ocp-power-automation/ocp4-playbooks-extras
      - ocp-power-automation/ocp4-upi-powervm
      - ocp-power-automation/ocp-power-automation.github.io
    require_self_approval: false

# Lower bounds in number of lines changed; XS is assumed to be zero.
size:
  s:   10
  m:   30
  l:   100
  xl:  500
  xxl: 1000

config_updater:
  maps:
    config/prow/config.yaml:
      name: config
    config/prow/plugins.yaml:
      name: plugins
    config/prow/labels.yaml:
      name: label-config
    config/jobs/**/*.{yaml,yml}:
      name: job-config
      gzip: true

welcome:
  - repos:
      - IBM/raksh
    message_template: "Welcome @{{.AuthorLogin}}! <br><br>It looks like this is your first PR to <a href='https://github.com/{{.Org}}/{{.Repo}}'>{{.Org}}/{{.Repo}}</a> ðŸŽ‰. Please refer to our [pull request process documentation](https://github.com/IBM/raksh/blob/master/CONTRIBUTING.md#pull-requests) to help your PR have a smooth ride to approval. <br><br>You will be prompted by a bot to use commands during the review process. Do not be afraid to follow the prompts! It is okay to experiment. [Here is the bot commands documentation](https://go.k8s.io/bot-commands). <br><br>You can also check if {{.Org}}/{{.Repo}} has [its own contribution guidelines](https://github.com/{{.Org}}/{{.Repo}}/tree/master/CONTRIBUTING.md). <br><br>Thank you, and welcome to Project Raksh. :smiley:"

require_matching_label:
  - missing_label: needs-kind
    org: IBM
    repo: raksh
    issues: true
    prs: true
    regexp: ^kind/
  - missing_label: needs-kind
    org: ppc64le-cloud
    repo: test-infra
    issues: true
    prs: true
    regexp: ^kind/
  - missing_label: needs-kind
    org: ocp-power-automation
    repo: ocp4-upi-powervs
    issues: true
    prs: true
    regexp: ^kind/
  - missing_label: needs-kind
    org: ocp-power-automation
    repo: ocp4-playbooks
    issues: true
    prs: true
    regexp: ^kind/

retitle:
  allow_closed_issues: true

plugins:
  IBM/raksh:
    plugins:
      - approve
      - assign
      - blunderbuss
      - cat
      - dog
      - golint
      - goose
      - heart
      - help
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - mergecommitblocker
      - owners-label
      - pony
      - retitle
      - shrug
      - size
      - skip
      - trigger
      - verify-owners
      - welcome
      - wip
      - yuks

  ppc64le-cloud:
    plugins:
      - approve
      - assign
      - blunderbuss
      - cat
      - config-updater
      - dog
      - golint
      - goose
      - heart
      - help
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - mergecommitblocker
      - owners-label
      - pony
      - retitle
      - shrug
      - size
      - skip
      - trigger
      - verify-owners
      - welcome
      - wip
      - yuks

  ocp-power-automation:
    plugins:
      - approve
      - assign
      - blunderbuss
      - cat
      - config-updater
      - dog
      - golint
      - goose
      - heart
      - help
      - hold
      - label
      - lgtm
      - lifecycle
      - mergecommitblocker
      - owners-label
      - pony
      - retitle
      - shrug
      - size
      - skip
      - trigger
      - verify-owners
      - welcome
      - wip
      - yuks

  openshift-powervs:
    plugins:
      - approve
      - assign
      - cat
      - config-updater
      - dog
      - golint
      - goose
      - heart
      - help
      - hold
      - label
      - lgtm
      - lifecycle
      - mergecommitblocker
      - owners-label
      - pony
      - retitle
      - shrug
      - size
      - skip
      - trigger
      - verify-owners
      - welcome
      - wip
      - yuks

  trigger-prow/test-trigger:
    plugins:
      - approve
      - assign
      - cat
      - config-updater
      - dog
      - golint
      - goose
      - heart
      - help
      - hold
      - label
      - lgtm
      - lifecycle
      - mergecommitblocker
      - owners-label
      - pony
      - retitle
      - shrug
      - size
      - skip
      - trigger
      - verify-owners
      - welcome
      - wip
      - yuks

  Rajalakshmi-Girish/etcd:
    plugins:
      - approve
      - assign
      - cat
      - config-updater
      - dog
      - golint
      - goose
      - heart
      - help
      - hold
      - label
      - lgtm
      - lifecycle
      - mergecommitblocker
      - owners-label
      - pony
      - retitle
      - shrug
      - size
      - skip
      - trigger
      - verify-owners
      - welcome
      - wip
      - yuks

external_plugins:
  ocp-power-automation:
  - name: cherrypick
    events:
      - issue_comment
      - pull_request
  ocp-power-automation/ocp4-upi-powervs:
  - name: mergeable
    events:
      - issue_comment
      - pull_request
  ocp-power-automation/ocp4-upi-powervm:
  - name: mergeable
    events:
      - issue_comment
      - pull_request
  ocp-power-automation/ocp4-playbooks:
  - name: mergeable
    events:
      - issue_comment
      - pull_request
  ocp-power-automation/openshift-install-power:
  - name: mergeable
    events:
      - issue_comment
      - pull_request
