postsubmits:
 ppc64le-cloud/docker-ce-build:
    - name: postsubmit-test-docker-staging
      cluster: k8s-ppc64le-cluster
      labels:
        preset-build-docker: "true"
      decorate: true
      run_if_changed: 'env/test-staging.list'
      branches:
        - main
      reporter_config:
        slack:
          channel: 'prow-job-notifications'
          job_states_to_report:
           - success
           - failure
           - error
          report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
      spec:
        containers:
        - image: quay.io/powercloud/docker-ce-build@sha256:2231f00d1b1af02c018ea8f2f2ee2a890174d0bb0ce7067d128519e442776cbc
          resources:
            requests:
              cpu: "8000m"
            limits:
              cpu: "8000m"
          command:
          - /bin/bash
          args:
          - -c
          - |
            set -o errexit
            set -o nounset
            set -o pipefail
            set -o xtrace

            #Timestamp file from the tracking branch (required to access the proper s3 directory)
            TIMESTAMP_FILE=postsubmit-build-docker

            FILE_URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/prow-job-tracking/job/${TIMESTAMP_FILE}"

            echo "* Retrieve the timestamp file from the tracking branch: ${FILE_URL} *"
            curl -o env/date.list ${FILE_URL}
            cat env/date.list

            echo "* Start prow-test-docker.sh *"
            ./prow-test-docker.sh staging
            rc=$?
            [ $rc != 0 ] && echo "ERROR: prow-test-docker exited with code:$rc"
            exit $rc

          securityContext:
            privileged: true

    - name: postsubmit-test-docker-release
      cluster: k8s-ppc64le-cluster
      labels:
        preset-build-docker: "true"
      decorate: true
      run_if_changed: 'env/test-release.list'
      branches:
        - main
      reporter_config:
        slack:
          channel: 'prow-job-notifications'
          job_states_to_report:
           - success
           - failure
           - error
          report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
      spec:
        containers:
        - image: quay.io/powercloud/docker-ce-build@sha256:2231f00d1b1af02c018ea8f2f2ee2a890174d0bb0ce7067d128519e442776cbc
          resources:
            requests:
              cpu: "8000m"
            limits:
              cpu: "8000m"
          command:
          - /bin/bash
          args:
          - -c
          - |
            set -o errexit
            set -o nounset
            set -o pipefail
            set -o xtrace

            #Timestamp file from the tracking branch (required to access the proper s3 directory)
            TIMESTAMP_FILE=postsubmit-build-docker

            FILE_URL="https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/prow-job-tracking/job/${TIMESTAMP_FILE}"

            echo "* Retrieve the timestamp file from the tracking branch: ${FILE_URL} *"
            curl -o env/date.list ${FILE_URL}
            cat env/date.list

            echo "* Start prow-test-docker.sh *"
            ./prow-test-docker.sh release
            rc=$?
            [ $rc != 0 ] && echo "ERROR: prow-test-docker exited with code:$rc"
            exit $rc

          securityContext:
            privileged: true
