periodics:
  - name: periodic-gcs-logs-cleanup
    decorate: true
    interval: 12h
    spec:
      volumes:
        - name: gcs-cred
          secret:
            secretName: gcs-credentials
      containers:
        - image: quay.io/powercloud/all-in-one:0.1
          command:
            - /bin/bash
          volumeMounts:
            - name: gcs-cred
              mountPath: /etc/gcs-cred
              readOnly: true
          args:
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail
              set -o xtrace
              go get  github.com/ppc64le-cloud/gcs-cleaner
              cat >config.yml <<EOL
              - dir: logs/periodic-kubernetes-bazel-test-ppc64le
                daysLimit: 15
              - dir: logs/periodic-kubernetes-conformance-test-ppc64le
                daysLimit: 7
              - dir: logs/periodic-kubernetes-containerd-conformance-test-ppc64le
                daysLimit: 7
              EOL
              $(go env GOPATH)/bin/gcs-cleaner
