periodics:
  - name: docker-all-in-one-test
    labels:
      preset-secrets: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 2h
    spec:
      containers:
      - image: quay.io/alunsin/all_in_one_dind
        command:
        - /bin/bash
        args:
        - -c
        - |
          bash /usr/local/bin/dockerd-entrypoint.sh &
          docker run hello-world
          docker run alpine
          docker ps -a
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-root
          mountPath: /var/lib/docker
      restartPolicy: Never
      terminationGracePeriodSeconds: 18
      volumes:
      - name: docker-root
        emptyDir: {}
