periodics:
  - name: periodic-golang-master-build-ppc64le
    cluster: k8s-ppc64le-cluster
    decorate: true
    cron: "50 1/1 * * *"
    spec:
      containers:
        - image: golang:1.17
          resources:
            requests:
              cpu: "2000m"
            limits:
              cpu: "2000m"
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash
              set -o errexit
              set -o nounset
              set -o pipefail
              set -o xtrace
              cd $HOME
              git clone https://github.com/golang/go.git
              cd go/src
              GITCOMMIT=$(git rev-parse --short HEAD)

              status_code=$(curl -sL -w "%{http_code}" http://build-bot.prow:8090/build?project=golang/master\&commit=$GITCOMMIT -o /dev/null)
              if [[ "$status_code" -ne 200 ]] ; then
                echo "time to build"
                ./make.bash
                cd ../..;rm -rf go/.git
                tar -czvf go.tar.gz go
                curl -v -X POST http://build-bot.prow:8090/build --fail -H 'Content-Type: multipart/form-data' -F file=@go.tar.gz -F source=github.com/golang/go.git -F commit=$GITCOMMIT -F project=golang/master
              else
                echo "$GITCOMMIT build already exist, hence skipping it"
              fi
