periodics:
  - name: knative-eventing-main-periodic
    labels:
      preset-knative-powervs: "true"
    decorate: true
    cron: "0 4 * * *"
    extra_refs:
      - base_ref: main
        org: ppc64le-cloud
        repo: knative-tkn-upstream-ci
        workdir: true
      - base_ref: main
        org: knative
        repo: eventing
    spec:
      containers:
        - image: quay.io/powercloud/knative-prow-tests:latest
          resources:
            requests:
              cpu: "1500m"
            limits:
              cpu: "1500m"
          command:
            - runner.sh
          args:
            - bash
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail
              set -o xtrace

              TIMESTAMP=$(date +%s)
              K8S_BUILD_VERSION=$(curl https://storage.googleapis.com/k8s-release-dev/ci/latest.txt)

              trap 'source cluster-setup.sh delete' EXIT

              source cluster-setup.sh create
              pushd $GOPATH/src/github.com/$ORG/$KNATIVE_REPO

              . /tmp/adjust.sh
              ./test/e2e-tests.sh --run-tests
              popd

          env:
            - name: ORG
              value: knative
            - name: KNATIVE_REPO
              value: eventing
            - name: KNATIVE_RELEASE
              value: main
            - name: SYSTEM_NAMESPACE
              value: knative-eventing
            - name: SCALE_CHAOSDUCK_TO_ZERO
              value: "1"
